[package]
name = "server"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bytes = "1"
figment = { version = "0.10", features = ["toml"] }
futures-util = { version = "0.3", features = ["sink"] }
humantime = "2"
humantime-serde = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-util = { version = "0.7", features = ["codec", "rt"] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "agent-witness"
path = "src/main.rs"
